services:
  app:
    build:
        context: .
    container_name: app-update-service
    restart: "no"
    command: bash -c "alembic upgrade head && python -m app"
    environment:
      - app_host=0.0.0.0
      - app_port=8080
      - app_api_key=secret_key
      - app_crm_url_base=http://host.docker.internal:8000
      - postgres_host=postgresql
      - postgres_port=5432
      - postgres_user=user
      - postgres_password=password
      - postgres_db=test
    volumes:
      - file_storage:/persistent/file_storage
    ports:
      - 8080:8080

  postgresql:
    image: postgres
    container_name: app-update-service-postgresql
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: app-update-service-adminer
    restart: "no"
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: brade
    ports:
      - 10000:8080

volumes:
  file_storage:
